"""add username to backoffice_users

Revision ID: 49e52d8063ab
Revises: 94bcb7d3d512
Create Date: 2026-02-14 01:57:33.761696
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e52d8063ab'
down_revision: Union[str, None] = '94bcb7d3d512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backoffice_users', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_backoffice_users_username'), 'backoffice_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backoffice_users_username'), table_name='backoffice_users')
    op.drop_column('backoffice_users', 'username')
    # ### end Alembic commands ###
