"""initial postgres migration

Revision ID: 76ab156db31b
Revises: 
Create Date: 2026-02-14 04:41:46.481899
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ab156db31b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentic_components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('input', 'processing', 'output', 'data_source', 'utility', name='componentcategory', native_enum=False, length=20), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('uses_llm', sa.Boolean(), nullable=False),
    sa.Column('default_provider_id', sa.String(length=100), nullable=True),
    sa.Column('default_model', sa.String(length=255), nullable=True),
    sa.Column('provider_type', sa.Enum('text', 'image', 'vision', 'none', name='providertype', native_enum=False, length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentic_components_type'), 'agentic_components', ['type'], unique=True)
    op.create_table('backoffice_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backoffice_users_email'), 'backoffice_users', ['email'], unique=True)
    op.create_index(op.f('ix_backoffice_users_username'), 'backoffice_users', ['username'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('component_api_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('api_route', sa.String(length=255), nullable=True),
    sa.Column('request_mapping', sa.JSON(), nullable=False),
    sa.Column('response_mapping', sa.JSON(), nullable=False),
    sa.Column('pass_through_condition', sa.JSON(), nullable=True),
    sa.Column('compression_threshold', sa.Integer(), nullable=True),
    sa.Column('executor_type', sa.Enum('api_call', 'data_source', 'pass_through', 'composite', name='executortype', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['agentic_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_api_config_component_id'), 'component_api_config', ['component_id'], unique=False)
    op.create_table('component_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'textarea', 'select', 'number', 'image', 'tags', name='fieldtype', native_enum=False, length=20), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['agentic_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_fields_component_id'), 'component_fields', ['component_id'], unique=False)
    op.create_table('component_output_schema',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('output_key', sa.String(length=100), nullable=False),
    sa.Column('output_type', sa.Enum('text', 'image', 'persona_name', 'persona_description', name='outputtype', native_enum=False, length=25), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['agentic_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_output_schema_component_id'), 'component_output_schema', ['component_id'], unique=False)
    op.create_table('component_ports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('in_', 'out', name='portdirection', native_enum=False, length=5), nullable=False),
    sa.Column('port_type', sa.Enum('text', 'adapter', name='porttype', native_enum=False, length=10), nullable=False),
    sa.Column('handle_id', sa.String(length=100), nullable=False),
    sa.Column('max_connections', sa.Integer(), nullable=True),
    sa.Column('is_dynamic', sa.Boolean(), nullable=False),
    sa.Column('max_dynamic', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['agentic_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_ports_component_id'), 'component_ports', ['component_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_project_name'), 'projects', ['project_name'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('consistent_characters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistent_characters_project_id'), 'consistent_characters', ['project_id'], unique=False)
    op.create_index(op.f('ix_consistent_characters_user_id'), 'consistent_characters', ['user_id'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_event_name'), 'event_logs', ['event_name'], unique=False)
    op.create_index(op.f('ix_event_logs_project_id'), 'event_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_event_logs_session_id'), 'event_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_event_logs_user_id'), 'event_logs', ['user_id'], unique=False)
    op.create_table('flows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('graph_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flows_project_id'), 'flows', ['project_id'], unique=False)
    op.create_index(op.f('ix_flows_user_id'), 'flows', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flows_user_id'), table_name='flows')
    op.drop_index(op.f('ix_flows_project_id'), table_name='flows')
    op.drop_table('flows')
    op.drop_index(op.f('ix_event_logs_user_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_session_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_project_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_name'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_consistent_characters_user_id'), table_name='consistent_characters')
    op.drop_index(op.f('ix_consistent_characters_project_id'), table_name='consistent_characters')
    op.drop_table('consistent_characters')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_component_ports_component_id'), table_name='component_ports')
    op.drop_table('component_ports')
    op.drop_index(op.f('ix_component_output_schema_component_id'), table_name='component_output_schema')
    op.drop_table('component_output_schema')
    op.drop_index(op.f('ix_component_fields_component_id'), table_name='component_fields')
    op.drop_table('component_fields')
    op.drop_index(op.f('ix_component_api_config_component_id'), table_name='component_api_config')
    op.drop_table('component_api_config')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_backoffice_users_username'), table_name='backoffice_users')
    op.drop_index(op.f('ix_backoffice_users_email'), table_name='backoffice_users')
    op.drop_table('backoffice_users')
    op.drop_index(op.f('ix_agentic_components_type'), table_name='agentic_components')
    op.drop_table('agentic_components')
    # ### end Alembic commands ###
