"""add agentic_components table

Revision ID: 7be935b4a6b0
Revises: 49e52d8063ab
Create Date: 2026-02-14 02:58:12.158530
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be935b4a6b0'
down_revision: Union[str, None] = '49e52d8063ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentic_components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('input', 'processing', 'output', 'data_source', 'utility', name='componentcategory', native_enum=False, length=20), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('uses_llm', sa.Boolean(), nullable=False),
    sa.Column('default_provider_id', sa.String(length=100), nullable=True),
    sa.Column('default_model', sa.String(length=255), nullable=True),
    sa.Column('provider_type', sa.Enum('text', 'image', 'vision', 'none', name='providertype', native_enum=False, length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentic_components_type'), 'agentic_components', ['type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agentic_components_type'), table_name='agentic_components')
    op.drop_table('agentic_components')
    # ### end Alembic commands ###
