"""add consistent_characters table

Revision ID: 89c4a0afdd85
Revises: 0609cd851d20
Create Date: 2026-02-14 03:18:59.261359
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c4a0afdd85'
down_revision: Union[str, None] = '0609cd851d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consistent_characters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistent_characters_project_id'), 'consistent_characters', ['project_id'], unique=False)
    op.create_index(op.f('ix_consistent_characters_user_id'), 'consistent_characters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consistent_characters_user_id'), table_name='consistent_characters')
    op.drop_index(op.f('ix_consistent_characters_project_id'), table_name='consistent_characters')
    op.drop_table('consistent_characters')
    # ### end Alembic commands ###
