"""add component_fields, component_ports, component_api_config, component_output_schema tables

Revision ID: e55a85b264ee
Revises: 7be935b4a6b0
Create Date: 2026-02-14 03:00:08.545121
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55a85b264ee'
down_revision: Union[str, None] = '7be935b4a6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_api_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('api_route', sa.String(length=255), nullable=True),
    sa.Column('request_mapping', sa.JSON(), nullable=False),
    sa.Column('response_mapping', sa.JSON(), nullable=False),
    sa.Column('pass_through_condition', sa.JSON(), nullable=True),
    sa.Column('compression_threshold', sa.Integer(), nullable=True),
    sa.Column('executor_type', sa.Enum('api_call', 'data_source', 'pass_through', 'composite', name='executortype', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['agentic_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_api_config_component_id'), 'component_api_config', ['component_id'], unique=False)
    op.create_table('component_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'textarea', 'select', 'number', 'image', 'tags', name='fieldtype', native_enum=False, length=20), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['agentic_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_fields_component_id'), 'component_fields', ['component_id'], unique=False)
    op.create_table('component_output_schema',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('output_key', sa.String(length=100), nullable=False),
    sa.Column('output_type', sa.Enum('text', 'image', 'persona_name', 'persona_description', name='outputtype', native_enum=False, length=25), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['agentic_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_output_schema_component_id'), 'component_output_schema', ['component_id'], unique=False)
    op.create_table('component_ports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('in_', 'out', name='portdirection', native_enum=False, length=5), nullable=False),
    sa.Column('port_type', sa.Enum('text', 'adapter', name='porttype', native_enum=False, length=10), nullable=False),
    sa.Column('handle_id', sa.String(length=100), nullable=False),
    sa.Column('max_connections', sa.Integer(), nullable=True),
    sa.Column('is_dynamic', sa.Boolean(), nullable=False),
    sa.Column('max_dynamic', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['agentic_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_ports_component_id'), 'component_ports', ['component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_component_ports_component_id'), table_name='component_ports')
    op.drop_table('component_ports')
    op.drop_index(op.f('ix_component_output_schema_component_id'), table_name='component_output_schema')
    op.drop_table('component_output_schema')
    op.drop_index(op.f('ix_component_fields_component_id'), table_name='component_fields')
    op.drop_table('component_fields')
    op.drop_index(op.f('ix_component_api_config_component_id'), table_name='component_api_config')
    op.drop_table('component_api_config')
    # ### end Alembic commands ###
